language: cpp
dist: bionic

script: cmake . && make -j2 VERBOSE=1 && ./bleb_test
compiler:
  - clang
  - gcc
os:
  - linux
  - osx

# AddressSanitizer on Travis linux instances is a hot pile of shit
matrix:
  allow_failures:
    - os: linux
